CONFIG_ZCYPHAL=y
CONFIG_ZCYPHAL_CAN_LOOPBACK=y
CONFIG_ZCYPHAL_TRACE=y
CONFIG_ZCYPHAL_LOG_LEVEL_DBG=y
CONFIG_CAN=y
CONFIG_CAN_LOOPBACK=y
CONFIG_CAN_LOG_LEVEL_DBG=y
CONFIG_HWINFO=y
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=4096
